// Generated by android-icons/scripts/generate-icon-packs.mjs. Do not edit.
import CoreGraphics
import MapConductorIcons

/// Map symbols from the us pack. Selection is always explicit.
public enum UnitedStatesMapIcons {
    /// United States post office.
    public static let postOffice = MapIconGlyph(
        id: "us.post_office",
        commands: [
            .moveTo(CGPoint(x: 12, y: 2)),
            .lineTo(CGPoint(x: 22, y: 7)),
            .lineTo(CGPoint(x: 2, y: 7)),
            .close,
            .moveTo(CGPoint(x: 3, y: 9)),
            .lineTo(CGPoint(x: 21, y: 9)),
            .lineTo(CGPoint(x: 21, y: 12)),
            .lineTo(CGPoint(x: 3, y: 12)),
            .close,
            .moveTo(CGPoint(x: 4, y: 12)),
            .lineTo(CGPoint(x: 7, y: 12)),
            .lineTo(CGPoint(x: 7, y: 19)),
            .lineTo(CGPoint(x: 4, y: 19)),
            .close,
            .moveTo(CGPoint(x: 9, y: 12)),
            .lineTo(CGPoint(x: 12, y: 12)),
            .lineTo(CGPoint(x: 12, y: 19)),
            .lineTo(CGPoint(x: 9, y: 19)),
            .close,
            .moveTo(CGPoint(x: 14, y: 12)),
            .lineTo(CGPoint(x: 17, y: 12)),
            .lineTo(CGPoint(x: 17, y: 19)),
            .lineTo(CGPoint(x: 14, y: 19)),
            .close,
            .moveTo(CGPoint(x: 19, y: 12)),
            .lineTo(CGPoint(x: 21, y: 12)),
            .lineTo(CGPoint(x: 21, y: 19)),
            .lineTo(CGPoint(x: 19, y: 19)),
            .close,
            .moveTo(CGPoint(x: 2, y: 19)),
            .lineTo(CGPoint(x: 22, y: 19)),
            .lineTo(CGPoint(x: 22, y: 22)),
            .lineTo(CGPoint(x: 2, y: 22)),
            .close,
        ]
    )

    /// United States police station.
    public static let policeStation = MapIconGlyph(
        id: "us.police_station",
        commands: [
            .moveTo(CGPoint(x: 12, y: 2)),
            .lineTo(CGPoint(x: 21, y: 5)),
            .lineTo(CGPoint(x: 20, y: 14)),
            .curveTo(end: CGPoint(x: 12, y: 22), control1: CGPoint(x: 19, y: 19), control2: CGPoint(x: 15, y: 21)),
            .curveTo(end: CGPoint(x: 4, y: 14), control1: CGPoint(x: 9, y: 21), control2: CGPoint(x: 5, y: 19)),
            .lineTo(CGPoint(x: 3, y: 5)),
            .close,
        ]
    )

    /// United States Interstate highway.
    public static let interstate = MapIconGlyph(
        id: "us.interstate",
        commands: [
            .moveTo(CGPoint(x: 3, y: 5)),
            .curveTo(end: CGPoint(x: 12, y: 2), control1: CGPoint(x: 7, y: 3), control2: CGPoint(x: 9, y: 4)),
            .curveTo(end: CGPoint(x: 21, y: 5), control1: CGPoint(x: 15, y: 4), control2: CGPoint(x: 17, y: 3)),
            .lineTo(CGPoint(x: 20, y: 14)),
            .curveTo(end: CGPoint(x: 12, y: 22), control1: CGPoint(x: 19, y: 19), control2: CGPoint(x: 15, y: 21)),
            .curveTo(end: CGPoint(x: 4, y: 14), control1: CGPoint(x: 9, y: 21), control2: CGPoint(x: 5, y: 19)),
            .close,
        ]
    )
}
